name: Deploy Convex Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Deploy Convex dev
        working-directory: packages/backend
        run: npx convex deploy
        env:
          CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEV_DEPLOYMENT }}
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEV_AUTH_TOKEN }}
